### ISSUE TITLE
File annotation and Ruby "magic" comments

### ISSUE THREAD

**Issue by cfurrow** [rubyatscale/code_ownership#21]
It seems that `code_ownership` requires that the file annotation be a comment on the very first line of a Ruby file, but this conflicts with Ruby "magic" comments, like `# frozen_string_literal: true`, which is also required to be on the first line of a file.

When digging into the code of `code_ownership`, I see a comment that alluded to an idea that it used to (?) check the first two lines of a Ruby file for the annotation, but the code does not align with that comment anymore.

> ... if the annotation isn't in the first two lines ...

Code lines: https://github.com/rubyatscale/code_ownership/blob/main/lib/code_ownership/private/ownership_mappers/file_annotations.rb#L57-L61

```ruby
sig { params(filename: String).returns(T.nilable(CodeTeams::Team)) }
def file_annotation_based_owner(filename)
  # If for a directory is named with an ownable extension, we need to skip
  # so File.foreach doesn't blow up below. This was needed because Cypress
  # screenshots are saved to a folder with the test suite filename.
  return if File.directory?(filename)
  return unless File.file?(filename)

  # The annotation should be on line 1 but as of this comment
  # there's no linter installed to enforce that. We therefore check the
  # first line (the Ruby VM makes a single `read(1)` call for 8KB),
  # and if the annotation isn't in the first two lines we assume it
  # doesn't exist.

  line_1 = File.foreach(filename).first

  return if !line_1

  begin
    team = line_1[TEAM_PATTERN, :team]
  rescue ArgumentError => ex
    if ex.message.include?('invalid byte sequence')
      team = nil
    else
      raise
    end
  end

  return unless team 
  #...snip
end
```

**Comment by cfurrow** [comment]
Updating the file annotation matcher to look at every line in a Ruby file until it reaches the first line that does not start with a `#`: https://github.com/rubyatscale/code_ownership/pull/20

**Comment by alexevanczuk** [comment]
Hi @cfurrow thank you for filing this issue and creating a PR to help `code_ownership` be usable in your application. I want to make sure that your issue is resolved and wanted to cover some points first:

> I see a comment that alluded to an idea that it used to (?) check the first two lines of a Ruby file for the annotation, but the code does not align with that comment anymore.

This actually is from the fact that Gusto used to have both `# @team Team` AND `# @mission Mission`. `mission` was an organizational concept that we used to have at Gusto that we've removed internally after some reorgs, and we also believe it didn't apply generically to other orgs, so we removed the functionality, but forgot to remove the comment.

> [other magic comments are] required to be on the first line of a file.

We haven't found this to be the case at Gusto – does this come from a Rubocop you're using? We have cops requiring the use of frozen string literal but they don't require it to be on the first line. I hate to ask if you want to change your own app's config, but I'm wondering if it would work to simply turn off that constraint?

> Updating the file annotation matcher to look at every line in a Ruby file until it reaches the first line that does not start with a #

The main reason that we only look at the first line (or in the past, the first two lines), was a performance consideration. Gusto has a large monolith, so `bin/codewnership validate` and other APIs like `CodeOwnership.for_file(...)` need to stay performant. I haven't pulled your fork yet into our monolith and done any benchmarking, but my guess would be that doing a regex match on every line rather than just the first line will cause a non-negligible performance change. If you're not able to loosen the constraint as described above (I'd be happy to zoom pair with you if you are having trouble with this), I was wondering if, perhaps, we could allow `config/code_ownership.yml` to allow this to be configured so that we can have our cake and eat it too.

Thank you again!! Let me know what you think about all of this.

**Comment by cfurrow** [comment]
Hi @alexevanczuk, and thank you for such a thorough response!

> does this come from a Rubocop you're using

Upon re-checking, Rubocop does not seem to raise an error when moving the magic comments below the first line. That was new to me, and now I regret not checking that before submitting this PR.

> but my guess would be that doing a regex match on every line rather than just the first line will cause a non-negligible performance change

I would assume that as well. My hope was that the check for each line beginning with `#` up to the first line that does not start with `#` would keep the overall cost low, but if there were dozens of comment lines it could cause slow downs.

> Let me know what you think about all of this.

I think I can safely close this PR without merging for now. Since our Rubocop setup is not complaining anymore like I thought it would, we can safely move the magic comments below the `# @team` annotations.

Thank you again for the very thoughtful and thorough reply!

**Comment by alexevanczuk** [comment]
Thank you @cfurrow for your response. Nothing to regret, and if you (or anyone else reading this) later find that the requirement that these team annotations live at the top of the file a blocker to their adoption or continued use of `code_ownership`, please let me know and we can continue to brainstorm.

> ... would keep the overall cost low
Your approach to address mitigate performance issues does sound reasonable – thanks for being so thoughtful there.

> I think I can safely close this PR without merging for now.

Sounds good! Again please continue to file issues related to this or anything else that comes up – we appreciate your feedback.
