### ISSUE TITLE
Add method to return ownership adoption (percentage of files with ownership)

### ISSUE THREAD

**Issue by vaot** [rubyatscale/code_ownership#58]
One key metric to track with any project is how the percentage of files with ownership is changing over time. This can be accomplished now using the interfaces under `Private`. Do you think it would be reasonable to implement something like this?

```ruby
def percentage_of_files_with_ownership(files: Private.tracked_files)
  files = (Private.tracked_files & files)
  allow_list = Dir.glob(Private.configuration.unowned_globs)

  files_by_mapper = Private.files_by_mapper(files)
  files_not_mapped_at_all = files_by_mapper.select { |_file, mapper_descriptions| mapper_descriptions.count == 0 }.keys

  files_without_owners = (files_not_mapped_at_all - allow_list).count
  files_tracked_count = (files_by_mapper.keys - allow_list).count

  with_owners_count = files_tracked_count - files_without_owners

  (with_owners_count / files_tracked_count.to_f) * 100
end
```
(Using code from `1.32.2` for the sake of demonstration)

cc @alexevanczuk 
Let me know what you think and I will get a PR ready.

**Comment by ashleywillard** [comment]
Hi @vaot! Sorry for the delayed response. We think this is a great idea! It would also be nice to be able to access the total count of files with owners and of unowned files. We were thinking of adding this functionality as a CLI command that would print out the file counts, percentage of owned files, and file counts per team.

Is this something that you'd like to take on? We understand that some time has passed since you opened this issue and that circumstances may be different.
